# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build
    displayName: Build
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - template: Pipelines/Steps/build-steps.yml

  - stage: "release_dev"
    displayName: Release Development
    dependsOn: ["build"]
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    variables:
      - name: ResourceGroup
        value: 
      - name: AzureSubscription
        value: 
      - name: environment
        value: 'DEV'
    jobs:
      - deployment: 'dev'
        displayName: 'Dev'
        pool:
          vmImage: windows-latest
        environment: ${{ variables.ResourceGroup }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Pipelines/Steps/deployment-steps.yml
  
                
  - stage: "release_prd"
    displayName: Release Productiont
    dependsOn: ["release_dev"]
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    variables:
      - name: ResourceGroup
        value: 
      - name: AzureSubscription
        value: 
      - name: environment
        value: 'PRD'
    jobs:
      - deployment: 'prd'
        displayName: 'PRD'
        pool:
          vmImage: windows-latest
        environment: ${{ variables.ResourceGroup }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Pipelines/Steps/deployment-steps.yml

